tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "chezmoi"
brew "neofetch"
brew "tree"
brew "wget"
brew "mtr"

cask "1password"
cask "appcleaner"
cask "cleanshot"
cask "folx"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "logseq"
cask "notion"
cask "obsidian"
cask "stats"
cask "viscosity"
cask "visual-studio-code"